version: 1.0.{build}
image: Visual Studio 2017

install: 
  - nuget restore

build:
  project: ITunesLibraryParser.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: Q4IyaxOG4nDYXjCelbf08+bGIos8E6inE5m4x47ghjdtbGZYVgbdDkn0QESq5CAU

before_test:
   ps: Write-Host "Before Test Hooks here..."
   
after_test:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:path32 -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"/domain:single ITunesLibraryParserTests/bin/debug/ITunesLibraryParser.Tests.dll ITunesLibraryParser.EndToEndTests/bin/debug/ITunesLibraryParser.EndToEndTests.dll" -output:coverage.xml
  - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

deploy:
- provider: NuGet
  api_key:
    secure: JIfexXpciz2JvCDWEAd84Pee5dlo5Ik45rNg1v5eVhdRAH7jugdV4+xh9ROxzeUt