version: 1.0.{build}
image: Visual Studio 2017

install: 
  - nuget restore

build:
  project: ITunesLibraryParser.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: Q4IyaxOG4nDYXjCelbf08+bGIos8E6inE5m4x47ghjdtbGZYVgbdDkn0QESq5CAU

after_test:
  - cmd: call RunCoverage.cmd 
  - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

deploy:
- provider: NuGet
  api_key:
    secure: JIfexXpciz2JvCDWEAd84Pee5dlo5Ik45rNg1v5eVhdRAH7jugdV4+xh9ROxzeUt