version: 1.0.{build}
image: Visual Studio 2017
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: JIfexXpciz2JvCDWEAd84Pee5dlo5Ik45rNg1v5eVhdRAH7jugdV4+xh9ROxzeUt